name: uxmSkyblock
version: 0.4.0
main: net.cengiz1.uxmskyblock.UxmSkyblockPlugin
api-version: 1.21
author: cengiz1x
softdepend: [FastAsyncWorldEdit, Vault, PlaceholderAPI]

permissions:
  skyblock.time:
    description: Allows locking the island time (day/night)
    default: op
  skyblock.admin:
    description: uxmSkyblock administrator permission
    default: op
